[project]
name = "nrbug"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.116.1",
    "newrelic==10.15.0",
    "uvicorn==0.36.0",
    "uvloop==0.21.0"
]
